// ignore: file_names
List<String> buttonNames = [
  'Serial Handshake',
  'Home Arm',
  'Check User Height',
  'Start wash',
  'Start Cream',
  'Start dryer',
  'Kapi 1 Ac',
  'Kapi 1 Kapat',
  'Kapi 2 Ac',
  'Kapi 2 Kapat',
  'Kapi1 Kilitle',
  'Kapi1 Kilit Ac',
  'Kapi2 Kilitle',
  'Kapi2 Kilit Ac',
  'Ozon ac',
  'Ozon Kapa',
  'Valf1 Aç',
  'Valf1 Kapa',
  'Valf2 Aç',
  'Valf2 Kapa',
  'Valf3 Aç',
  'Valf3 Kapa',
  'Valf4 Aç',
  'Valf4 Kapa',
  'Valf5 Aç',
  'Valf5 Kapa',
  'Valf6 Aç',
  'Valf6 Kapa',
  'Valf7 Aç',
  'Valf7 Kapa',
  'Valf8 Aç',
  'Valf8 Kapa',
  'Pompa1 Aç',
  'Pompa1 Kapa',
  'Pompa2 Aç',
  'Pompa2 Kapa',
  'Pompa3 Aç',
  'Pompa3 Kapa',
  'Pompa4 Aç',
  'Pompa4 Kapa',
  'Pompa5 Aç',
  'Pompa5 Kapa',
  'Lamba Aç',
  'Lamba Kapa',
  'Sol Kapak Kilit Aç',
  'Sol Kapak Kilit Kapat',
  'Sağ Kapak Kilit Aç',
  'Sağ Kapak Kilit Kapat',
  'Kol Kilit Aç',
  'Kolu Kilitle',
  'Pompa6 Aç',
  'Pompa6 Kapat',
  'Ana Pompa 1 Aç',
  'Ana Pompa 1 Kapat',
  'Ana Pompa 2 Aç',
  'Ana Pompa 2 Kapat',
  'Su ısıtıcı Aç',
  'Su ısıtıcı Kapat',
  'Kurutucu Aç',
  'Kurutucu Kapat',
  'Lights Test',
  'Kol Aşağı 1 Saniye',
  'Kol Yukarı 1 Saniye',
  'Kolu Durdur',
  'Acil Modu Kapa',
  'Acil Modu Aç',
];
